layout_spectrum: 0.6833118807990104
typography_spectrum: 0.220557821681723
color:
  brandStrength: 0.7141778899822384
  lightness: 0.5883844387717545
  saturation: 0.6681579612195492
  rhythmicContrast: 0.9398226914927363
  brandColors:
    - '#0039FB'
    - '#70AAAF'
    - '#403C2E'
    - '#FFFDB6'
    - '#D99F66'
name: matryer
navigation:
  - name: Blog
    url: 'https://medium.com/@matryer'
    type: external
  - name: Twitter
    url: 'https://twitter.com/matryer'
    type: external
title: Mat Ryer
description: 'Gopher, developer, speaker, author, ally'
purpose:
  - type: external
    url: 'https://twitter.com/matryer'
    label: Follow @matryer on Twitter
  - type: external
    url: 'https://github.com/matryer'
    label: GitHub
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FcAWlv2SeQus%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DcAWlv2SeQus&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FcAWlv2SeQus%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Golang UK Conference
          url: 'https://www.youtube.com/channel/UC9ZNrGdT2aAdrNbX78lbNlQ'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - golang
        - uk
        - london
        - computer science
        - google
      description: >-
        Whether for internal use, or destined for open-source stardom, writing
        good packages with clean and clear APIs will greatly increase the chance
        that the code is used and reused. Explore best practices, goals, and
        idioms that help make beautiful packages.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=cAWlv2SeQus&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=cAWlv2SeQus&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=cAWlv2SeQus&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=cAWlv2SeQus&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=cAWlv2SeQus&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=cAWlv2SeQus'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=cAWlv2SeQus
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=cAWlv2SeQus
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=cAWlv2SeQus'
      title: Golang UK Conference 2017 | Mat Ryer - Writing Beautiful Packages in Go
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
author:
  name: Mat Ryer
url: 'https://matryer.com/'
